export const jobsDB = [
  {
    title: "Frontend Developer",
    company: "Ingenious Management Consulting Ltd.",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Website Developer",
    company: "SuperMoney",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer",
    company: "",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "Genesys",
    Location: "Markham, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Internal Tools",
    company: "Sound Cloud",
    Location: "Berlin, Germany",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Software Developer 2",
    company: "Iniut",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "Genesys",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Frontend Enginner",
    company: "GitLab",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Software Developer 2",
    company: "Affirm",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "Konrad",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Software Developer I",
    company: "varicent",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "The Home Depot",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "Epsilon Solutions Ltd.",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Enginner",
    company: "DataVisor",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-End Developer",
    company: "Build with Assembly",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-End Developer",
    company: "Evolving Web",
    Location: "Montreal, QC",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-End Developer",
    company: "wisedocs",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Web Applications Developer",
    company: "Toronto Metroplotian School",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Development Engineer",
    company: "orum",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Frontend Engineer",
    company: "JerryAI",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "VRIZE",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Programmer I (Web Developer)",
    company: "Siana Health",
    Location: "Toronto, ON",
    jobURL:
      "https://contact2.mshri.on.ca/hr/DEFAULT.ASP?page=jobDetail&job=1970",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Digital Learning Build Coordinator",
    company: "Humber College",
    Location: "Toronto, ON",
    jobURL:
      "https://humber.taleo.net/careersection/hbr_ex/jobdetail.ftl?job=29880",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "React Front End Developer (PL570)",
    company: "Paralucent",
    Location: "Toronto, ON",
    jobURL:
      "https://careers.paralucent.com/o/react-front-end-developer-pl570/c/new?source=LinkedIn",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Website Developer",
    company: "LyfeDesign",
    Location: "Toronto, ON",
    jobURL:
      "https://www.careers-page.com/lyfedesign/job/L4YVV495?utm_medium=free_job_board&utm_source=linkedin",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Web CMS Developer Specialist",
    company: "Brainrider",
    Location: "Toronto, ON",
    jobURL:
      "https://ats.rippling.com/brainrider/jobs/8023f2c1-6dec-4ba4-8c80-d8f5ae3a9f62?jobSite=LinkedIn",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-end developer",
    company: "Triunity",
    Location: "Toronto, ON",
    jobURL: "https://103.careerplug.com/jobs/2468197/apps/new",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Web Developer, Web Platform",
    company: "Robinhood",
    Location: "Toronto, ON",
    jobURL:
      "https://boards.greenhouse.io/robinhood/jobs/6023679?t=gh_src%3D&gh_jid=6023679&gh_src=ed898e781us",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "ReactJS Developer",
    company: "Webisoft",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/3948821657",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Developer II (Frontend)",
    company: "Koho",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/3937799344",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer - React - Web",
    company: "Kraken Digital Asset Exchange",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/3949546149",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Full Stack Software Engineer",
    company: "Warner Music Group",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/3948084598/",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer II",
    company: "Zonda",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/3944015421/",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Website Developer (Extension)",
    company: "Humber College",
    Location: "Etobiko, ON",
    jobURL: "Null",
    Response: "Started",
    Updates: "Email",
    Offers: "Tue, Jun 18",
  },
  {
    title: "Full Stack Software Engineer",
    company: "Loop Financial",
    Location: "Toronto ON",
    jobURL:
      "https://ats.rippling.com/loop-careers/jobs/a021cca1-fa0b-4f6e-82c1-c6fa6c9e03f1",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Software Engineer II",
    company: "Scribd",
    Location: "Toronto ON",
    jobURL: "https://jobs.lever.co/scribd/634c9fc9-b8ba-48c8-90e0-f763d7726c6f",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Jr. Back-End Developer",
    company: "linusmediagroup",
    Location: "Toronto ON",
    jobURL: "https://linusmediagroup.com/ft-junior-backend-developer",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "Mootiva",
    Location: "Lisboa, Lisboa",
    jobURL:
      "https://mootiva.catsone.com/careers/113611-General/jobs/16479130-Frontend-Developer/",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Software Engineer",
    company: "PolicyMe logo",
    Location: "Toronto ON",
    jobURL:
      "https://jobs.lever.co/policyme/b6b41cf8-fd9f-48d8-864c-671b53fc7042",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Junior Developer",
    company: "Expansion",
    Location: "Toronto ON",
    jobURL: "https://www.linkedin.com/jobs/view/4055170807",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "UI Designer",
    company: "",
    Location: "Toronto ON",
    jobURL: "https://www.linkedin.com/jobs/view/4062329608",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "Pine - Viewed Application",
    Location: "Toronto ON",
    jobURL:
      "Check out this job at Pine:  https://www.linkedin.com/jobs/view/4075118562",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front send Developer",
    company: "Lumenalta",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "Sterb Canada Inc.",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Front End Developer",
    company: "Apex Mobile Media",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UX Designer (Hybrid)",
    company: "Canada Goose",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Engineer",
    company: "impact.com",
    Location: "Toronto ON",
    jobURL: "https://www.linkedin.com/jobs/view/4081024883",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UX/UI Designer (Hybrid)",
    company: "xanadu",
    Location: "Toronto ON",
    jobURL: "https://www.xanadu.ai/",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Frontend Developer (React)",
    company: "Levr.ai",
    Location: "Toronto ON",
    jobURL: "https://www.linkedin.com/jobs/view/4081851892",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "DAC",
    Location: "Toronto ON",
    jobURL: "https://www.linkedin.com/jobs/view/4078617598",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "MailChannels",
    Location: "Toronto ON",
    jobURL: "https://mailchannels.bamboohr.com/careers/10",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "UI/UX Designer",
    company: "Cova Software",
    Location: "Toronto ON",
    jobURL: "Check out this job at Cova Software:",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Software Developer - Full Stack",
    company: "Electric Mind",
    Location: "Toronto ON",
    jobURL:
      "https://jobs.lever.co/intelliware/759b57c3-a5c3-4698-af78-66b3591bb936?applicant_guid=0dfb4cc8-16a4-4920-952b-05d443568ce4&lever-origin=applied&lever-source%5B%5D=JobTarget%2CJobTarget%20Organic%20Sites%20Bundle&utm_source=JobTarget&utm_medium=JobTarget%20Organic%20Sites%20Bundle&utm_campaign=Junior%20Software%20Developer%20-%20Full%20Stack%20(759b57c3-a5c3-4698-af78-66b3591bb936)&_jtochash=egAwG7fmD7QDpsaX2idzME&_jtocprof=RJZnLmmV0YBGyNP09QB4rscMtV8FhJpD",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UI/UX Designer",
    company: "Swoon",
    Location: "Toronto ON",
    jobURL: "https://www.swoonstaffing.ca/",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer",
    company: "Rose Rocket",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Web UI/UX Developer",
    company: "Inorbital",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Front-end Developer",
    company: "Toolbx US Inc",
    Location: "Toronto ON",
    jobURL:
      "https://www.simplyhired.ca/job/Mm44U-EU-qG6z9tOGOGn1aXw0jp0neJVVwHmAi7Y7XNJAGBStqMCWA",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "Zensurance",
    Location: "Toronto ON",
    jobURL:
      "https://jobs.lever.co/zensurance/8c826995-0f86-4926-a2fe-223bcf8cf0ab",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Sr. Frontend Developer",
    company: "Wisedocs",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UI/UX Developer",
    company: "Sunrise Group Inc",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "TDS Personnel",
    Location: "Markham, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4085981709",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Web Developer",
    company: "Knix",
    Location: "Toronto ON",
    jobURL:
      "https://www.simplyhired.ca/job/PVTk3PDkFhT1W9qLJaYnZZm6BnHWvVAv63Jy9Hi1gD_sj6E2k70V5Q",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Web Developer",
    company: "Agency Analytics",
    Location: "Toronto ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "EQ Bank | Equitable Bank",
    Location: "Toronto ON",
    jobURL:
      "https://www.simplyhired.ca/job/CF5Yg6AN77wo2avV86QhMRpyYhJ209eRGrn22gmYBPamG18cZUFzVA",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "KUBRA",
    Location: "Mississauga, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4084896079",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UX/UI Developer",
    company: "Jonas Club Software",
    Location: "Markham, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4083287007",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Software Developer",
    company: "Rewind",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4092125803",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Front end Developer",
    company: "Amazech Solutions",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4093659151",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "UI/UX Designer",
    company: "Location Discord",
    Location: "Remote",
    jobURL:
      "https://discord.com/channels/486935104384532500/1309105109954723860",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "Technical Writer",
    company: "Caribbean",
    Location: "Remote",
    jobURL: "https://www.careers-page.com/thehivecareers/job/L848563V",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Full-Stack Engineer (Remote)",
    company: "Addy AI",
    Location: "Remote",
    jobURL:
      "https://addyai.notion.site/Full-Stack-Engineer-Remote-8e60887860d5408fbb6d31a9096a90a6",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Full Stack Developer",
    company: "Boosty Labs",
    Location: "Remote",
    jobURL: "",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "Frontend Software Developer – HTML / CSS / JavaScript",
    company: "Moneris",
    Location: "Remote",
    jobURL: "https://www.linkedin.com/jobs/view/4100053313",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-End Engineer (Remote)",
    company: "Canada - Remote ON",
    Location: "Remote",
    jobURL:
      "https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers/job/Front-End-Engineer--Remote-_R21315",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer, Frontend",
    company: "Proof",
    Location: "Remote",
    jobURL:
      "https://www.proofserve.com/careers/4520928005?gh_jid=4520928005&gh_src=2d1983cb5us#application",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "loblaw",
    Location: "Toronto, ON",
    jobURL:
      "https://careers.loblaw.ca/front-end-developer-ii-10-month-contract/job/PAF-LCL-1528B462-BB92-4699-8B7D-B653F2B15836_7580_1737393927_0",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "eLocal",
    Location: "Remote",
    jobURL: "https://www.linkedin.com/jobs/view/4140140428",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "React UI Developer",
    company: "Techedin",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4131919468",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Web Developer",
    company: "connexall",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer",
    company: "VTS",
    Location: "Toronto, ON",
    jobURL: "https://job-boards.greenhouse.io/vts/jobs/4497398005",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-End Web Developer",
    company: "pinnacle",
    Location: "Toronto, ON",
    jobURL: "https://job-boards.greenhouse.io/vts/jobs/4497398005",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developers-Health",
    company: "Zortech Solutions",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4153178120",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer",
    company: "Relay",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.lever.co/relayfi/c9e1dc17-ea52-4859-b4f2-2bf91a9a76c2",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-End Developer (AEM)",
    company: "Saatchi & Saatchi",
    Location: "Toronto, ON",
    jobURL: "https://careers-publicisgroupe.icims.com/jobs/95363/",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer I",
    company: "Retain",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.lever.co/includedhealth/71927e92-88ec-4481-8d12-00a2bcd9c41f",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "G-P",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Software Engineer",
    company: "Warner Music Group",
    Location: "Toronto, ON",
    jobURL: "https://jobs.lever.co/wmg/ecaadabc-2983-4b65-b86d-0326016de11a",
    Response: "Applied",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Senior Front-End Developer",
    company: "Wisedocs AI",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer, Frontend",
    company: "Proof",
    Location: "Toronto, ON",
    jobURL: "https://www.proofserve.com/careers/4520928005#application",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Full Stack Engineer, Onboarding",
    company: "Stripe",
    Location: "Toronto, ON",
    jobURL:
      "https://stripe.com/jobs/listing/full-stack-engineer-onboarding/6649844?gh_src=73vnei",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Senior Frontend Developer",
    company: "Kaizen Technologies",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4176767311",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front-end Engineer",
    company: "Faire WholeSale",
    Location: "Toronto, ON",
    jobURL:
      "https://job-boards.greenhouse.io/faire/jobs/7895148002?gh_jid=7895148002&gh_src=b84852fd2us",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UX / UI Designer",
    company: "Webster Team Development",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4176752170",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Engineer",
    company: "BuildOPS",
    Location: "Toronto, ON",
    jobURL: "https://buildops.com/careers/job-application/?gh_jid=5356104004",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Web Developer",
    company: "Shift4",
    Location: "Toronto, ON",
    jobURL:
      "https://job-boards.greenhouse.io/shift4/jobs/4657563007?gh_src=d53465cf7us",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Engineer, FinAuto",
    company: "Amazon",
    Location: "Toronto, ON",
    jobURL:
      "https://www.amazon.jobs/en/jobs/2912525/front-end-engineer-finauto",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UX Designer",
    company: "Sago Mini",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4150855833",
    Response: "Applied",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Frontend Engineer",
    company: "Tailscale",
    Location: "Toronto, ON",
    jobURL: "https://job-boards.greenhouse.io/tailscale/jobs/4521895005",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "UX Engineer",
    company: "Assembled",
    Location: "Remote",
    jobURL:
      "https://jobs.ashbyhq.com/assembledhq/b1e813b8-cead-458a-9a55-090ad371b372",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Front-End Developer (UI Design System)",
    company: "Toku",
    Location: "Remote",
    jobURL: "https://jobs.lever.co/toku/7c2a558c-f3ce-4232-9330-93f9eae29417",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Web Developer",
    company: "Tree Top Staffing LLC",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4180906905",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Developer",
    company: "RBC",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.rbc.com/ca/en/job/R-0000103871/Software-Developer-NodeJS",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UI/UX Designer",
    company: "RBC",
    Location: "Toronto, ON",
    jobURL: "https://jobs.rbc.com/ca/en/job/R-0000115550/UI-UX-Designer",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Technical Developer",
    company: "",
    Location: "Toronto, ON",
    jobURL:
      "https://careers.lululemon.com/en_US/careers/JobDetail/Junior-Technical-Developer/47146",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Club Attendant",
    company: "Good Life Fitness",
    Location: "Toronto, ON",
    jobURL:
      "https://goodlifefitness.wd3.myworkdayjobs.com/en-US/Careers/job/Club-Attendant---Toronto-Yonge-Eglinton-Centre_JR106715",
    Response: "Rejected",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "Web Developer, Onboarding Experiences",
    company: "Robbinhood",
    Location: "Toronto, ON",
    jobURL:
      "https://job-boards.greenhouse.io/robinhood/jobs/6583442?t=gh_src=&gh_jid=6583442&gh_src=ed898e781us",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Front End Web Developer",
    company: "shift4",
    Location: "Toronto, ON",
    jobURL:
      "https://job-boards.greenhouse.io/shift4/jobs/4657563007?gh_src=d53465cf7us",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "Great Gulf Canada",
    Location: "Toronto, ON",
    jobURL: "https://jobs.dayforcehcm.com/en-US/greatgulf/GG/jobs/2747",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Jr. Digital Designer",
    company: "Insight Global",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4182670502",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "landbase",
    Location: "Mountain View, Toronto, Warsaw",
    jobURL:
      "https://jobs.ashbyhq.com/landbase/38294de8-dffc-4fbc-b56f-f6958c70348c?utm_source=K4qvG9z4EN",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "Great Gulf Canada",
    Location: "",
    jobURL: "",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "Frontend Engineer",
    company: "BitGO",
    Location: "Toronto, ON",
    jobURL: "https://boards.greenhouse.io/bitgo/jobs/7876628002",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Intermediate Fullstack Developer (Ruby & React)",
    company: "FullScript",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Laundry Utility Person",
    company: "Chelsea Hotel - Toronto",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Web Developer",
    company: "Content and Communications",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "React Developer",
    company: "Persistent Systems",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4178781295",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Front-End UX Developer (React, Next.js)",
    company: "Openscreen",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4184591256",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Website Developer",
    company: "Vena Solutions",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4172505947",
    Response: "Rejected",
    Updates: "Email",
    Offers: "",
  },
  {
    title: "Frontend Engineer, UX",
    company: "Chainlink Labs",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.ashbyhq.com/chainlink-labs/859edddc-0449-44a1-874f-778681ebc698?src=LinkedIn",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Software Engineer I, Retain",
    company: "Included Health",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4166591686",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Web Developer",
    company: "EDealer",
    Location: "Toronto, ON",
    jobURL:
      "https://ats.rippling.com/en-CA/einc/jobs/f7752254-1013-4e69-9472-cda4559417e6",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Frontend Engineer - Onboarding",
    company: "BitGO",
    Location: "Toronto, ON",
    jobURL:
      "https://ats.rippling.com/en-CA/einc/jobs/f7752254-1013-4e69-9472-cda4559417e6",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Software Developer - Full Stack",
    company: "",
    Location: "",
    jobURL: "",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "UI Developer",
    company: "Tata Consultancy Services",
    Location: "Toronto, ON",
    jobURL:
      "https://ats.rippling.com/en-CA/einc/jobs/f7752254-1013-4e69-9472-cda4559417e6",
    Response: "Rejected",
    Updates: "Nothing",
    Offers: "",
  },
  {
    title: "Triage Engineer",
    company: "Overflow",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer - Inventory position",
    company: "StackAdapt",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Software Engineer",
    company: "Cohere",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Front End Developer",
    company: "AgencyAnalytics",
    Location: "Toronto, ON",
    jobURL:
      "https://agencyanalytics.pinpointhq.com/en/postings/6f60b45e-d78f-4416-a86c-7f7be12f9800",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "UX/UI Designer (North York, ON)",
    company: "",
    Location: "",
    jobURL: "",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "Frontend Engineer",
    company: "",
    Location: "",
    jobURL: "",
    Response: "",
    Updates: "",
    Offers: "",
  },
  {
    title: "Intermediate Front End Software Developer - Patient Communication",
    company: "Jane App",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.lever.co/janeapp/5a425bc6-b9f7-41c3-89aa-dcee5b74a794/already-received?ms=1743160209682",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "Front End Engineer (Hybrid)",
    company: "Homebase",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.ashbyhq.com/homebase/dc067dae-0635-4657-838d-192a3a880cc0?utm_source=unique_code%2C+e.g.+utm_source%3DLinkedInPaid",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Technical Developer",
    company: "Encore Catering",
    Location: "Toronto, ON",
    jobURL:
      "https://ca.indeed.com/viewjob?jk=ca94b76c19cb2535&from=shareddesktop_copy",
    Response: "Talking Stages",
    Updates: "Messsage",
    Offers: "",
  },
  {
    title: "Front End Engineer II, Campaign Management",
    company: "Amazon",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "UI/UX Designer",
    company: "",
    Location: "Toronto, ON",
    jobURL: "",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "Technical Writer - Transit",
    company: "Cadre",
    Location: "Toronto, ON",
    jobURL:
      "https://dd0000000eplaeae.my.salesforce-sites.com/tech/ts2__JobDetails?jobId=a0xOK000000KjXFYA0&tSource=a16d0000000HT4uAAG",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "Technical Writer",
    company: "Toronto Transit Commission (TTC)",
    Location: "Toronto, ON",
    jobURL:
      "https://career17.sapsf.com/portalcareer?_s.crb=RNaRSnDmX8XsfuP1GxeKq8U5PKTgci57opbjrWBDiOI%253d",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "Frontend Developer",
    company: "UST",
    Location: "Toronto, ON",
    jobURL:
      "https://usource.ripplehire.com/candidate/?token=8YxWjpwDhdL62DFYUIcQ&lang=en&source=USTLINKEDIN&ref=USTLINKEDIN#detail/job/36076",
    Response: "Rejected",
    Updates: "Email Rejection",
    Offers: "",
  },
  {
    title: "Website Developer",
    company: "Absorb Software",
    Location: "Toronto, ON",
    jobURL: "https://www.linkedin.com/jobs/view/4206086247",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "UI/UX Designer",
    company: "Alcumus",
    Location: "Toronto, ON",
    jobURL:
      "https://alcumus.pinpointhq.com/postings/1d975d5b-25fd-4e29-a462-9db5447ddbf3",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
  {
    title: "Software Engineer",
    company: "Jerry AI",
    Location: "Toronto, ON",
    jobURL:
      "https://jobs.ashbyhq.com/Jerry/496766ef-be88-4f83-a375-3baade7f3933/application?utm_source=6Vdva5VPyD",
    Response: "Rejected",
    Updates: "No Response",
    Offers: "",
  },
  {
    title: "Junior Tech Developer",
    company: "Open Source Integrators (OSI)",
    Location: "Toronto, ON",
    jobURL: "https://opensourceintegrators.bamboohr.com/careers/57",
    Response: "Applied",
    Updates: "Waiting",
    Offers: "",
  },
];
