import { NextResponse } from "next/server";

export async function GET(request: Request) {
  return NextResponse.json([
    {
      Title: "Frontend Developer",
      Company: "Ingenious Management Consulting Ltd.",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Website Developer",
      Company: "SuperMoney",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer",
      Company: "",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "Genesys",
      Location: "Markham, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Internal Tools",
      Company: "Sound Cloud",
      Location: "Berlin, Germany",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Software Developer 2",
      Company: "Iniut",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "Genesys",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Frontend Enginner",
      Company: "GitLab",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Software Developer 2",
      Company: "Affirm",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "Konrad",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Software Developer I",
      Company: "varicent",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "The Home Depot",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "Epsilon Solutions Ltd.",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Enginner",
      Company: "DataVisor",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-End Developer",
      Company: "Build with Assembly",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-End Developer",
      Company: "Evolving Web",
      Location: "Montreal, QC",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-End Developer",
      Company: "wisedocs",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Web Applications Developer",
      Company: "Toronto Metroplotian School",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Development Engineer",
      Company: "orum",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Frontend Engineer",
      Company: "JerryAI",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "VRIZE",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Programmer I (Web Developer)",
      Company: "Siana Health",
      Location: "Toronto, ON",
      jobURL:
        "https://contact2.mshri.on.ca/hr/DEFAULT.ASP?page=jobDetail&job=1970",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Digital Learning Build Coordinator",
      Company: "Humber College",
      Location: "Toronto, ON",
      jobURL:
        "https://humber.taleo.net/careersection/hbr_ex/jobdetail.ftl?job=29880",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "React Front End Developer (PL570)",
      Company: "Paralucent",
      Location: "Toronto, ON",
      jobURL:
        "https://careers.paralucent.com/o/react-front-end-developer-pl570/c/new?source=LinkedIn",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Website Developer",
      Company: "LyfeDesign",
      Location: "Toronto, ON",
      jobURL:
        "https://www.careers-page.com/lyfedesign/job/L4YVV495?utm_medium=free_job_board&utm_source=linkedin",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Web CMS Developer Specialist",
      Company: "Brainrider",
      Location: "Toronto, ON",
      jobURL:
        "https://ats.rippling.com/brainrider/jobs/8023f2c1-6dec-4ba4-8c80-d8f5ae3a9f62?jobSite=LinkedIn",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-end developer",
      Company: "Triunity",
      Location: "Toronto, ON",
      jobURL: "https://103.careerplug.com/jobs/2468197/apps/new",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Web Developer, Web Platform",
      Company: "Robinhood",
      Location: "Toronto, ON",
      jobURL:
        "https://boards.greenhouse.io/robinhood/jobs/6023679?t=gh_src%3D&gh_jid=6023679&gh_src=ed898e781us",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "ReactJS Developer",
      Company: "Webisoft",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/3948821657",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Developer II (Frontend)",
      Company: "Koho",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/3937799344",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer - React - Web",
      Company: "Kraken Digital Asset Exchange",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/3949546149",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Full Stack Software Engineer",
      Company: "Warner Music Group",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/3948084598/",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer II",
      Company: "Zonda",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/3944015421/",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Website Developer (Extension)",
      Company: "Humber College",
      Location: "Etobiko, ON",
      jobURL: "Null",
      Response: "Started",
      Updates: "Email",
      Offers: "Tue, Jun 18",
    },
    {
      Title: "Full Stack Software Engineer",
      Company: "Loop Financial",
      Location: "Toronto ON",
      jobURL:
        "https://ats.rippling.com/loop-careers/jobs/a021cca1-fa0b-4f6e-82c1-c6fa6c9e03f1",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Software Engineer II",
      Company: "Scribd",
      Location: "Toronto ON",
      jobURL:
        "https://jobs.lever.co/scribd/634c9fc9-b8ba-48c8-90e0-f763d7726c6f",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Jr. Back-End Developer",
      Company: "linusmediagroup",
      Location: "Toronto ON",
      jobURL: "https://linusmediagroup.com/ft-junior-backend-developer",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "Mootiva",
      Location: "Lisboa, Lisboa",
      jobURL:
        "https://mootiva.catsone.com/careers/113611-General/jobs/16479130-Frontend-Developer/",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Software Engineer",
      Company: "PolicyMe logo",
      Location: "Toronto ON",
      jobURL:
        "https://jobs.lever.co/policyme/b6b41cf8-fd9f-48d8-864c-671b53fc7042",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Junior Developer",
      Company: "Expansion",
      Location: "Toronto ON",
      jobURL: "https://www.linkedin.com/jobs/view/4055170807",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "UI Designer",
      Company: "",
      Location: "Toronto ON",
      jobURL: "https://www.linkedin.com/jobs/view/4062329608",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "Pine - Viewed Application",
      Location: "Toronto ON",
      jobURL:
        "Check out this job at Pine:  https://www.linkedin.com/jobs/view/4075118562",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front send Developer",
      Company: "Lumenalta",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "Sterb Canada Inc.",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Front End Developer",
      Company: "Apex Mobile Media",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UX Designer (Hybrid)",
      Company: "Canada Goose",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Engineer",
      Company: "impact.com",
      Location: "Toronto ON",
      jobURL: "https://www.linkedin.com/jobs/view/4081024883",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UX/UI Designer (Hybrid)",
      Company: "xanadu",
      Location: "Toronto ON",
      jobURL: "https://www.xanadu.ai/",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Frontend Developer (React)",
      Company: "Levr.ai",
      Location: "Toronto ON",
      jobURL: "https://www.linkedin.com/jobs/view/4081851892",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "DAC",
      Location: "Toronto ON",
      jobURL: "https://www.linkedin.com/jobs/view/4078617598",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "MailChannels",
      Location: "Toronto ON",
      jobURL: "https://mailchannels.bamboohr.com/careers/10",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "UI/UX Designer",
      Company: "Cova Software",
      Location: "Toronto ON",
      jobURL: "Check out this job at Cova Software:",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Software Developer - Full Stack",
      Company: "Electric Mind",
      Location: "Toronto ON",
      jobURL:
        "https://jobs.lever.co/intelliware/759b57c3-a5c3-4698-af78-66b3591bb936?applicant_guid=0dfb4cc8-16a4-4920-952b-05d443568ce4&lever-origin=applied&lever-source%5B%5D=JobTarget%2CJobTarget%20Organic%20Sites%20Bundle&utm_source=JobTarget&utm_medium=JobTarget%20Organic%20Sites%20Bundle&utm_campaign=Junior%20Software%20Developer%20-%20Full%20Stack%20(759b57c3-a5c3-4698-af78-66b3591bb936)&_jtochash=egAwG7fmD7QDpsaX2idzME&_jtocprof=RJZnLmmV0YBGyNP09QB4rscMtV8FhJpD",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UI/UX Designer",
      Company: "Swoon",
      Location: "Toronto ON",
      jobURL: "https://www.swoonstaffing.ca/",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer",
      Company: "Rose Rocket",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Web UI/UX Developer",
      Company: "Inorbital",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Front-end Developer",
      Company: "Toolbx US Inc",
      Location: "Toronto ON",
      jobURL:
        "https://www.simplyhired.ca/job/Mm44U-EU-qG6z9tOGOGn1aXw0jp0neJVVwHmAi7Y7XNJAGBStqMCWA",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "Zensurance",
      Location: "Toronto ON",
      jobURL:
        "https://jobs.lever.co/zensurance/8c826995-0f86-4926-a2fe-223bcf8cf0ab",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Sr. Frontend Developer",
      Company: "Wisedocs",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UI/UX Developer",
      Company: "Sunrise Group Inc",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "TDS Personnel",
      Location: "Markham, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4085981709",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Web Developer",
      Company: "Knix",
      Location: "Toronto ON",
      jobURL:
        "https://www.simplyhired.ca/job/PVTk3PDkFhT1W9qLJaYnZZm6BnHWvVAv63Jy9Hi1gD_sj6E2k70V5Q",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Web Developer",
      Company: "Agency Analytics",
      Location: "Toronto ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "EQ Bank | Equitable Bank",
      Location: "Toronto ON",
      jobURL:
        "https://www.simplyhired.ca/job/CF5Yg6AN77wo2avV86QhMRpyYhJ209eRGrn22gmYBPamG18cZUFzVA",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "KUBRA",
      Location: "Mississauga, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4084896079",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UX/UI Developer",
      Company: "Jonas Club Software",
      Location: "Markham, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4083287007",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Software Developer",
      Company: "Rewind",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4092125803",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Front end Developer",
      Company: "Amazech Solutions",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4093659151",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title: "UI/UX Designer",
      Company: "Location Discord",
      Location: "Remote",
      jobURL:
        "https://discord.com/channels/486935104384532500/1309105109954723860",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title: "Technical Writer",
      Company: "Caribbean",
      Location: "Remote",
      jobURL: "https://www.careers-page.com/thehivecareers/job/L848563V",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Full-Stack Engineer (Remote)",
      Company: "Addy AI",
      Location: "Remote",
      jobURL:
        "https://addyai.notion.site/Full-Stack-Engineer-Remote-8e60887860d5408fbb6d31a9096a90a6",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Full Stack Developer",
      Company: "Boosty Labs",
      Location: "Remote",
      jobURL: "",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title: "Frontend Software Developer – HTML / CSS / JavaScript",
      Company: "Moneris",
      Location: "Remote",
      jobURL: "https://www.linkedin.com/jobs/view/4100053313",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-End Engineer (Remote)",
      Company: "Canada - Remote ON",
      Location: "Remote",
      jobURL:
        "https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers/job/Front-End-Engineer--Remote-_R21315",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer, Frontend",
      Company: "Proof",
      Location: "Remote",
      jobURL:
        "https://www.proofserve.com/careers/4520928005?gh_jid=4520928005&gh_src=2d1983cb5us#application",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "loblaw",
      Location: "Toronto, ON",
      jobURL:
        "https://careers.loblaw.ca/front-end-developer-ii-10-month-contract/job/PAF-LCL-1528B462-BB92-4699-8B7D-B653F2B15836_7580_1737393927_0",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "eLocal",
      Location: "Remote",
      jobURL: "https://www.linkedin.com/jobs/view/4140140428",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "React UI Developer",
      Company: "Techedin",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4131919468",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Web Developer",
      Company: "connexall",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer",
      Company: "VTS",
      Location: "Toronto, ON",
      jobURL: "https://job-boards.greenhouse.io/vts/jobs/4497398005",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-End Web Developer",
      Company: "pinnacle",
      Location: "Toronto, ON",
      jobURL: "https://job-boards.greenhouse.io/vts/jobs/4497398005",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developers-Health",
      Company: "Zortech Solutions",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4153178120",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer",
      Company: "Relay",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.lever.co/relayfi/c9e1dc17-ea52-4859-b4f2-2bf91a9a76c2",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-End Developer (AEM)",
      Company: "Saatchi & Saatchi",
      Location: "Toronto, ON",
      jobURL: "https://careers-publicisgroupe.icims.com/jobs/95363/",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer I",
      Company: "Retain",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.lever.co/includedhealth/71927e92-88ec-4481-8d12-00a2bcd9c41f",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "G-P",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Software Engineer",
      Company: "Warner Music Group",
      Location: "Toronto, ON",
      jobURL: "https://jobs.lever.co/wmg/ecaadabc-2983-4b65-b86d-0326016de11a",
      Response: "Applied",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Senior Front-End Developer",
      Company: "Wisedocs AI",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer, Frontend",
      Company: "Proof",
      Location: "Toronto, ON",
      jobURL: "https://www.proofserve.com/careers/4520928005#application",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Full Stack Engineer, Onboarding",
      Company: "Stripe",
      Location: "Toronto, ON",
      jobURL:
        "https://stripe.com/jobs/listing/full-stack-engineer-onboarding/6649844?gh_src=73vnei",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Senior Frontend Developer",
      Company: "Kaizen Technologies",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4176767311",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front-end Engineer",
      Company: "Faire WholeSale",
      Location: "Toronto, ON",
      jobURL:
        "https://job-boards.greenhouse.io/faire/jobs/7895148002?gh_jid=7895148002&gh_src=b84852fd2us",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UX / UI Designer",
      Company: "Webster Team Development",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4176752170",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Engineer",
      Company: "BuildOPS",
      Location: "Toronto, ON",
      jobURL: "https://buildops.com/careers/job-application/?gh_jid=5356104004",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Web Developer",
      Company: "Shift4",
      Location: "Toronto, ON",
      jobURL:
        "https://job-boards.greenhouse.io/shift4/jobs/4657563007?gh_src=d53465cf7us",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Engineer, FinAuto",
      Company: "Amazon",
      Location: "Toronto, ON",
      jobURL:
        "https://www.amazon.jobs/en/jobs/2912525/front-end-engineer-finauto",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UX Designer",
      Company: "Sago Mini",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4150855833",
      Response: "Applied",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Frontend Engineer",
      Company: "Tailscale",
      Location: "Toronto, ON",
      jobURL: "https://job-boards.greenhouse.io/tailscale/jobs/4521895005",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "UX Engineer",
      Company: "Assembled",
      Location: "Remote",
      jobURL:
        "https://jobs.ashbyhq.com/assembledhq/b1e813b8-cead-458a-9a55-090ad371b372",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Front-End Developer (UI Design System)",
      Company: "Toku",
      Location: "Remote",
      jobURL: "https://jobs.lever.co/toku/7c2a558c-f3ce-4232-9330-93f9eae29417",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Web Developer",
      Company: "Tree Top Staffing LLC",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4180906905",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Developer",
      Company: "RBC",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.rbc.com/ca/en/job/R-0000103871/Software-Developer-NodeJS",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UI/UX Designer",
      Company: "RBC",
      Location: "Toronto, ON",
      jobURL: "https://jobs.rbc.com/ca/en/job/R-0000115550/UI-UX-Designer",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Technical Developer",
      Company: "",
      Location: "Toronto, ON",
      jobURL:
        "https://careers.lululemon.com/en_US/careers/JobDetail/Junior-Technical-Developer/47146",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Club Attendant",
      Company: "Good Life Fitness",
      Location: "Toronto, ON",
      jobURL:
        "https://goodlifefitness.wd3.myworkdayjobs.com/en-US/Careers/job/Club-Attendant---Toronto-Yonge-Eglinton-Centre_JR106715",
      Response: "Rejected",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "Web Developer, Onboarding Experiences",
      Company: "Robbinhood",
      Location: "Toronto, ON",
      jobURL:
        "https://job-boards.greenhouse.io/robinhood/jobs/6583442?t=gh_src=&gh_jid=6583442&gh_src=ed898e781us",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Front End Web Developer",
      Company: "shift4",
      Location: "Toronto, ON",
      jobURL:
        "https://job-boards.greenhouse.io/shift4/jobs/4657563007?gh_src=d53465cf7us",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "Great Gulf Canada",
      Location: "Toronto, ON",
      jobURL: "https://jobs.dayforcehcm.com/en-US/greatgulf/GG/jobs/2747",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Jr. Digital Designer",
      Company: "Insight Global",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4182670502",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "landbase",
      Location: "Mountain View, Toronto, Warsaw",
      jobURL:
        "https://jobs.ashbyhq.com/landbase/38294de8-dffc-4fbc-b56f-f6958c70348c?utm_source=K4qvG9z4EN",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "Great Gulf Canada",
      Location: "",
      jobURL: "",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title: "Frontend Engineer",
      Company: "BitGO",
      Location: "Toronto, ON",
      jobURL: "https://boards.greenhouse.io/bitgo/jobs/7876628002",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Intermediate Fullstack Developer (Ruby & React)",
      Company: "FullScript",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Laundry Utility Person",
      Company: "Chelsea Hotel - Toronto",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Web Developer",
      Company: "Content and Communications",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "React Developer",
      Company: "Persistent Systems",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4178781295",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Front-End UX Developer (React, Next.js)",
      Company: "Openscreen",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4184591256",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Website Developer",
      Company: "Vena Solutions",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4172505947",
      Response: "Rejected",
      Updates: "Email",
      Offers: "",
    },
    {
      Title: "Frontend Engineer, UX",
      Company: "Chainlink Labs",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.ashbyhq.com/chainlink-labs/859edddc-0449-44a1-874f-778681ebc698?src=LinkedIn",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Software Engineer I, Retain",
      Company: "Included Health",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4166591686",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Web Developer",
      Company: "EDealer",
      Location: "Toronto, ON",
      jobURL:
        "https://ats.rippling.com/en-CA/einc/jobs/f7752254-1013-4e69-9472-cda4559417e6",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Frontend Engineer - Onboarding",
      Company: "BitGO",
      Location: "Toronto, ON",
      jobURL:
        "https://ats.rippling.com/en-CA/einc/jobs/f7752254-1013-4e69-9472-cda4559417e6",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Software Developer - Full Stack",
      Company: "",
      Location: "",
      jobURL: "",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title: "UI Developer",
      Company: "Tata Consultancy Services",
      Location: "Toronto, ON",
      jobURL:
        "https://ats.rippling.com/en-CA/einc/jobs/f7752254-1013-4e69-9472-cda4559417e6",
      Response: "Rejected",
      Updates: "Nothing",
      Offers: "",
    },
    {
      Title: "Triage Engineer",
      Company: "Overflow",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer - Inventory position",
      Company: "StackAdapt",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Software Engineer",
      Company: "Cohere",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Front End Developer",
      Company: "AgencyAnalytics",
      Location: "Toronto, ON",
      jobURL:
        "https://agencyanalytics.pinpointhq.com/en/postings/6f60b45e-d78f-4416-a86c-7f7be12f9800",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "UX/UI Designer (North York, ON)",
      Company: "",
      Location: "",
      jobURL: "",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title: "Frontend Engineer",
      Company: "",
      Location: "",
      jobURL: "",
      Response: "",
      Updates: "",
      Offers: "",
    },
    {
      Title:
        "Intermediate Front End Software Developer - Patient Communication",
      Company: "Jane App",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.lever.co/janeapp/5a425bc6-b9f7-41c3-89aa-dcee5b74a794/already-received?ms=1743160209682",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "Front End Engineer (Hybrid)",
      Company: "Homebase",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.ashbyhq.com/homebase/dc067dae-0635-4657-838d-192a3a880cc0?utm_source=unique_code%2C+e.g.+utm_source%3DLinkedInPaid",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Technical Developer",
      Company: "Encore Catering",
      Location: "Toronto, ON",
      jobURL:
        "https://ca.indeed.com/viewjob?jk=ca94b76c19cb2535&from=shareddesktop_copy",
      Response: "Talking Stages",
      Updates: "Messsage",
      Offers: "",
    },
    {
      Title: "Front End Engineer II, Campaign Management",
      Company: "Amazon",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "UI/UX Designer",
      Company: "",
      Location: "Toronto, ON",
      jobURL: "",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "Technical Writer - Transit",
      Company: "Cadre",
      Location: "Toronto, ON",
      jobURL:
        "https://dd0000000eplaeae.my.salesforce-sites.com/tech/ts2__JobDetails?jobId=a0xOK000000KjXFYA0&tSource=a16d0000000HT4uAAG",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "Technical Writer",
      Company: "Toronto Transit Commission (TTC)",
      Location: "Toronto, ON",
      jobURL:
        "https://career17.sapsf.com/portalcareer?_s.crb=RNaRSnDmX8XsfuP1GxeKq8U5PKTgci57opbjrWBDiOI%253d",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "Frontend Developer",
      Company: "UST",
      Location: "Toronto, ON",
      jobURL:
        "https://usource.ripplehire.com/candidate/?token=8YxWjpwDhdL62DFYUIcQ&lang=en&source=USTLINKEDIN&ref=USTLINKEDIN#detail/job/36076",
      Response: "Rejected",
      Updates: "Email Rejection",
      Offers: "",
    },
    {
      Title: "Website Developer",
      Company: "Absorb Software",
      Location: "Toronto, ON",
      jobURL: "https://www.linkedin.com/jobs/view/4206086247",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "UI/UX Designer",
      Company: "Alcumus",
      Location: "Toronto, ON",
      jobURL:
        "https://alcumus.pinpointhq.com/postings/1d975d5b-25fd-4e29-a462-9db5447ddbf3",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
    {
      Title: "Software Engineer",
      Company: "Jerry AI",
      Location: "Toronto, ON",
      jobURL:
        "https://jobs.ashbyhq.com/Jerry/496766ef-be88-4f83-a375-3baade7f3933/application?utm_source=6Vdva5VPyD",
      Response: "Rejected",
      Updates: "No Response",
      Offers: "",
    },
    {
      Title: "Junior Tech Developer",
      Company: "Open Source Integrators (OSI)",
      Location: "Toronto, ON",
      jobURL: "https://opensourceintegrators.bamboohr.com/careers/57",
      Response: "Applied",
      Updates: "Waiting",
      Offers: "",
    },
  ]);
}
