import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const kantumruySans = localFont({
  src: "./fonts/KantumruyPro-VariableFont_wght.ttf",
  variable: "--font-kantumruy-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Personal Recipe Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kantumruySans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
